SIMPLE:
  BATCH_SIZE: 256
  NHEADS: 3
  DIM_FEEDFORWARD: 128
  NTRANSFORMERS: 1
  N_FF_LAYERS: 2
  EPOCHS: 200

NINE_HEADS:
  BATCH_SIZE: 256
  NHEADS: 9
  DIM_FEEDFORWARD: 128
  NTRANSFORMERS: 1
  N_FF_LAYERS: 2
  EPOCHS: 200

DEPTH_FF:
  BATCH_SIZE: 256
  NHEADS: 3
  DIM_FEEDFORWARD: 128
  NTRANSFORMERS: 1
  N_FF_LAYERS: 10
  EPOCHS: 200

LARGE_FF:
  BATCH_SIZE: 256
  NHEADS: 3
  DIM_FEEDFORWARD: 2048
  NTRANSFORMERS: 1
  N_FF_LAYERS: 2
  EPOCHS: 200

MANY_TRANSFORMERS:
  BATCH_SIZE: 256
  NHEADS: 3
  DIM_FEEDFORWARD: 128
  NTRANSFORMERS: 16
  N_FF_LAYERS: 2
  EPOCHS: 200

BLEND:
  BATCH_SIZE: 256
  NHEADS: 3
  DIM_FEEDFORWARD: 128
  NTRANSFORMERS: 8
  N_FF_LAYERS: 4
  EPOCHS: 200